### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Bronya-Rayi** [dwardchan/Jarvis-HomePage#1]
编译后也是同样的效果，显示不正常，而且便签，常用网站之类的功能都没有
![image](https://user-images.githubusercontent.com/47048823/97167661-29f5c900-17c2-11eb-8f09-957020ff2232.png)

**Comment by dwardchan** [comment]
不要引用jarvis.vue那个文件就行，我在尝试加一些自己的东西（three.js）

**Comment by Bronya-Rayi** [comment]
好的，成功运行，大佬tql
